// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://jhjympznbobcgdltnjfk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpoanltcHpuYm9iY2dkbHRuamZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM5NjIyNDcsImV4cCI6MjA4OTUzODI0N30.Ra5CyogWe63u6-rTHAv849ZQvPlwp0jwbTIneOkLYNk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
